language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
env:
  - BOTO_CONFIG=/tmp/nowhere
before_install:
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
      echo "No pull requests can be sent to the master branch" 1>&2;
      exit 1;
    fi
  - sudo apt-get update
  - sudo apt-get --reinstall install -qq language-pack-en language-pack-de
  - sudo apt-get install swig
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then travis_retry pip install -r requirements-py26.txt; fi
  - travis_retry pip install -r requirements.txt
script: python tests/test.py default
